site_name: Elasticsearch and ELK Stack
site_url: https://ggsood.github.io/elk-stack
site_author: Gaurav Sood

# Copyright
copyright: 'Copyright &copy; 2020 Gaurav Sood'

theme:
  name: material
  favicon: assets/images/favicon.ico
  logo: assets/images/favicon.ico
  custom_dir: overrides
  include_search_page: false
  search_index_only: false
  palette:
    scheme: default
    primary: blue
    accent: light blue
  font:
    text: Fira Code
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.superfences

# Page tree
nav:
  - Welcome: index.md
  - Elasticsearch:
    - What is Elasticsearch: elasticsearch/What-is-Elasticsearch.md
    - Finding your feet: elasticsearch/Finding-your-feet.md
    - Basic Concepts: elasticsearch/Basic-Concepts.md
    - Exloring Cluster: elasticsearch/Exploring-Cluster.md

